import { describe, expect, it } from "vitest";
import { HuggingFaceEmbeddingRetrievalEngine } from "../../src/adapters/huggingface/huggingface-embedding-retrieval-engine.js";
import { LexicalRetrievalEngine } from "../../src/adapters/memory/lexical-retrieval-engine.js";
import { createRetrievalEngine } from "../../src/modules/platform/retrieval-engine-factory.js";

describe("createRetrievalEngine", () => {
  it("creates lexical engine by default", () => {
    const engine = createRetrievalEngine({
      NODE_ENV: "development",
      DATABASE_URL: "postgresql://localhost/test",
      APP_NAME: "sellora",
      APP_HOST: "0.0.0.0",
      APP_PORT: 3000,
      DEFAULT_CURRENCY: "AED",
      RETRIEVAL_PROVIDER: "lexical",
      RETRIEVAL_TOP_K_DEFAULT: 10,
      HUGGINGFACE_API_TOKEN: undefined,
      HUGGINGFACE_EMBEDDINGS_URL: undefined,
      HUGGINGFACE_EMBEDDINGS_MODEL: "intfloat/multilingual-e5-small",
      OPERATOR_API_TOKEN: undefined,
      PAYMENT_WEBHOOK_SECRET: undefined,
      KARRIO_WEBHOOK_SECRET: undefined,
      NOTIFICATION_PROVIDER: "memory",
      NOTIFICATION_FROM_EMAIL: undefined,
      NOTIFICATION_REPLY_TO_EMAIL: undefined,
      RESEND_API_KEY: undefined,
      RESEND_BASE_URL: "https://api.resend.com",
      KARRIO_BASE_URL: undefined,
      KARRIO_API_KEY: undefined,
      KARRIO_PROVIDER_NAME: "karrio",
      KARRIO_CARRIER_ID: undefined,
      KARRIO_SERVICE: undefined,
      KARRIO_SHIPPER_POSTAL_CODE: undefined,
      KARRIO_SHIPPER_COUNTRY_CODE: undefined,
      KARRIO_SHIPPER_CITY: undefined,
      KARRIO_SHIPPER_STATE_CODE: undefined,
      KARRIO_SHIPPER_ADDRESS_LINE1: undefined,
      KARRIO_SHIPPER_ADDRESS_LINE2: undefined,
      KARRIO_SHIPPER_COMPANY_NAME: undefined,
      KARRIO_SHIPPER_PERSON_NAME: undefined,
      KARRIO_SHIPPER_PHONE_NUMBER: undefined,
      KARRIO_SHIPPER_EMAIL: undefined,
      KARRIO_RECIPIENT_POSTAL_CODE: undefined,
      KARRIO_RECIPIENT_COUNTRY_CODE: undefined,
      KARRIO_RECIPIENT_CITY: undefined,
      KARRIO_RECIPIENT_STATE_CODE: undefined,
      KARRIO_RECIPIENT_ADDRESS_LINE1: undefined,
      KARRIO_RECIPIENT_ADDRESS_LINE2: undefined,
      KARRIO_RECIPIENT_COMPANY_NAME: undefined,
      KARRIO_RECIPIENT_PERSON_NAME: undefined,
      KARRIO_RECIPIENT_PHONE_NUMBER: undefined,
      KARRIO_RECIPIENT_EMAIL: undefined,
      KARRIO_PARCEL_WEIGHT: undefined,
      KARRIO_PARCEL_WEIGHT_UNIT: undefined,
      KARRIO_PARCEL_LENGTH: undefined,
      KARRIO_PARCEL_WIDTH: undefined,
      KARRIO_PARCEL_HEIGHT: undefined,
      KARRIO_PARCEL_DISTANCE_UNIT: undefined,
      GLOBAL_AUTONOMY_ENABLED: false,
      DEFAULT_MINIMUM_MARGIN_PCT: 25,
      DEFAULT_MAXIMUM_RISK_SCORE: 45,
      DEFAULT_MINIMUM_LOCALIZATION_SCORE: 60
    });

    expect(engine).toBeInstanceOf(LexicalRetrievalEngine);
  });

  it("creates huggingface engine when configured", () => {
    const engine = createRetrievalEngine({
      NODE_ENV: "development",
      DATABASE_URL: "postgresql://localhost/test",
      APP_NAME: "sellora",
      APP_HOST: "0.0.0.0",
      APP_PORT: 3000,
      DEFAULT_CURRENCY: "AED",
      RETRIEVAL_PROVIDER: "huggingface",
      RETRIEVAL_TOP_K_DEFAULT: 10,
      HUGGINGFACE_API_TOKEN: "hf_test",
      HUGGINGFACE_EMBEDDINGS_URL: "https://embeddings.sellora.test/embed",
      HUGGINGFACE_EMBEDDINGS_MODEL: "intfloat/multilingual-e5-small",
      OPERATOR_API_TOKEN: undefined,
      PAYMENT_WEBHOOK_SECRET: undefined,
      KARRIO_WEBHOOK_SECRET: undefined,
      NOTIFICATION_PROVIDER: "memory",
      NOTIFICATION_FROM_EMAIL: undefined,
      NOTIFICATION_REPLY_TO_EMAIL: undefined,
      RESEND_API_KEY: undefined,
      RESEND_BASE_URL: "https://api.resend.com",
      KARRIO_BASE_URL: undefined,
      KARRIO_API_KEY: undefined,
      KARRIO_PROVIDER_NAME: "karrio",
      KARRIO_CARRIER_ID: undefined,
      KARRIO_SERVICE: undefined,
      KARRIO_SHIPPER_POSTAL_CODE: undefined,
      KARRIO_SHIPPER_COUNTRY_CODE: undefined,
      KARRIO_SHIPPER_CITY: undefined,
      KARRIO_SHIPPER_STATE_CODE: undefined,
      KARRIO_SHIPPER_ADDRESS_LINE1: undefined,
      KARRIO_SHIPPER_ADDRESS_LINE2: undefined,
      KARRIO_SHIPPER_COMPANY_NAME: undefined,
      KARRIO_SHIPPER_PERSON_NAME: undefined,
      KARRIO_SHIPPER_PHONE_NUMBER: undefined,
      KARRIO_SHIPPER_EMAIL: undefined,
      KARRIO_RECIPIENT_POSTAL_CODE: undefined,
      KARRIO_RECIPIENT_COUNTRY_CODE: undefined,
      KARRIO_RECIPIENT_CITY: undefined,
      KARRIO_RECIPIENT_STATE_CODE: undefined,
      KARRIO_RECIPIENT_ADDRESS_LINE1: undefined,
      KARRIO_RECIPIENT_ADDRESS_LINE2: undefined,
      KARRIO_RECIPIENT_COMPANY_NAME: undefined,
      KARRIO_RECIPIENT_PERSON_NAME: undefined,
      KARRIO_RECIPIENT_PHONE_NUMBER: undefined,
      KARRIO_RECIPIENT_EMAIL: undefined,
      KARRIO_PARCEL_WEIGHT: undefined,
      KARRIO_PARCEL_WEIGHT_UNIT: undefined,
      KARRIO_PARCEL_LENGTH: undefined,
      KARRIO_PARCEL_WIDTH: undefined,
      KARRIO_PARCEL_HEIGHT: undefined,
      KARRIO_PARCEL_DISTANCE_UNIT: undefined,
      GLOBAL_AUTONOMY_ENABLED: false,
      DEFAULT_MINIMUM_MARGIN_PCT: 25,
      DEFAULT_MAXIMUM_RISK_SCORE: 45,
      DEFAULT_MINIMUM_LOCALIZATION_SCORE: 60
    });

    expect(engine).toBeInstanceOf(HuggingFaceEmbeddingRetrievalEngine);
  });
});
